dist: trusty
sudo: false

language: node_js
node_js:
  - '10'


cache:
  directories:
    - ./node_modules


script:
  # - ng lint
  - ng build --prod
  # - ng test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  - firebase deploy
