dist: trusty
sudo: false

language: node_js
node_js:
  - '10'


cache:
  directories:
    - ./node_modules

branches:
  only:
  - master

script:
  - ./node_modules/.bin/eslint './src/app/*.ts' --fix
  - ng build --prod
  # - ng test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
  # - firebase deploy says firebase: command not found
 - echo "Deploy!!"

install:
  - npm install -g firebase-tools

deploy:
  provider: firebase
  token:
    secure: "Ih2z1ONDHsf5JWGAZQ7xoSD4pPfKsc99CC6OZ5eBPPOOVkNIexLMaQteEcXHD6HqGBcAYW9/4WD+48YLq2eO/Tl+JnaAuoKyF6K8pjhqsu5aoXcvyuTreV5bdYeoq0Ao2M1N5WgerEhRRUBsqpHjy7cfZAvQlPsRqFTpPG49VvXTDTX9J+eXk/DUY8GzWTXzbutHco5/QmI7OTOIaKWyyqEnaGFyeSDgLz1hfpbCrdUlZ5UCn1tkgi8cINrbe/3INODyzhs5Ha6PJHGYB7kx9VhUR5VHVG/wBeyVDpFcwjm09L0mHR3nw32zXOViZ6mxJYyN238SzL6P/958JSVcE8ujG31yGRYAbL/bEET09W7wDwlVbJ9p8L1E0UfoBCbNNlw8w+lPsN+1cpGI0OydR/B+uaBe1a6Zub+SX8yEGgpFhjG5dA1Og/pXlK81Tqape2jSVH2dv4EoJkG8Fkbhe73eqXmvmBelvlJeW/MH1Gb2enxBEqiMyXTa6qH+7z7wqolB8dp+2bzpLDRM6fnTm8D0T3YIecinX96F7h2tiW2vfeBVqmM16QT2yKpr3y+/hOeOJHxXrBaQ/ifFjU+QxN7u5tKzBM7ZyxOGLTYxCiNdEaOAjxkyJ/4cfCiakiSkZztcKMVkDqU6DAQLPFj2btmKY/Qae3OI+Lkz75FTvns="